### ISSUE TITLE
Where is clipboard.min.js?

### ISSUE THREAD

**Issue by larosel** [Basaingeal/Razor.Clipboard#36]
<script src="_content/CurrieTechnologies.Razor.Clipboard/clipboard.min.js"></script>

It's not in repository and not found error in browser.

**Comment by Basaingeal** [comment]
Sorry for not seeing this. I didn't have my issue notifications on correctly.
The `clipboard.min.js` file is not in the repository. It's created at build time and packaged into the NuGet package by the CI/CD process.

I'm not sure why you're getting a 404 for it though. The minified version of the file _was_ added recently. Are you using version `1.1.0`? Also, are you seeing this in a Blazor Server or a Blazor WebAssembly application?

**Comment by SouthHeaven** [comment]
Hi,

I have this exact problem (v`1.2.2`).
It's happening when I change this environment variable :
ASPNETCORE_ENVIRONMENT : Development > Production

(It's working in `Development` but not in `Production`).
As a workaround, I had to extract the `clipboard.min.js` and save it to a custom folder in `wwwroot`.
Then I modified the `_Host.cshtml` : 

```
    <script src="_framework/blazor.server.js"></script>
    <script src="scripts/CurrieTechnologies.Razor.Clipboard/clipboard.min.js"></script>
    <!-- Not working in another environment than Development
    <script src="_content/CurrieTechnologies.Razor.Clipboard/clipboard.min.js"></script>
    -->
```
