### ISSUE TITLE
Deprecated, but what are the alternatives ?

### ISSUE THREAD

**Issue by Wndrr** [Basaingeal/Razor.Clipboard#366]
The readme.md says that this project is now deprecated but makes no mention of the currently favored solution. 

Is there a preferred solution or is this deprecated for lack of maintenance ?

**Comment by Basaingeal** [comment]
This library is not in-fact deprecated. The note in the readme says that [CurrieTechnologies.Blazor.Clipboard](https://github.com/Basaingeal/Blazor.Clipboard) is deprecated, but this library is [CurrieTechnologies.*Razor*.Clipboard]. 

The Blazor vs Razor distinction is from the early days of Blazor where server-side and client-side Blazor needed different libraries. Eventually the server-side version libraries started working with client-side as well, so the library targeting the client-side was deprecated.

The note is a little bit outdated, I'll admit, but also CurrieTechnologies.Blazor.Clipboard is still out there on NuGet.org and might be where people look first. I can probably make the note a bit less prominent though, as it can be confusing and most people won't care anyway.

**Comment by Wndrr** [comment]
My bad ! I must have read that too fast and assume, because of the similarity, that the names were identical !

Thanks for your quick answer !
